port: 8080
loglevel: info

printer:
  address: 192.168.1.10
  username: maker
  apikey: apikey

prusaConnect:
  enable: true
  cameraToken: camera token
  fingerprint: fingerprint

timelapse:
  enable: true
  interval: 20 #seconds